### ISSUE TITLE
Keeps waiting for panamax to start

### ISSUE THREAD

**Issue by amlee** [CenturyLinkLabs/panamax-coreos#29]
The Mac OSX installation keeps waiting for panamax to start forever:
==> panamax-vm: Restarting Panamax
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[516]: [8511f82d] -job stop(PMX_UI) = OK (0)
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[1284]: PMX_UI
==> panamax-vm: Aug 19 20:50:52 panamax-vm systemd[1]: Starting Panamax UI...
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[516]: 2014/08/19 20:50:52 DELETE /v1.12/containers/PMX_UI?force=1
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[516]: [8511f82d] +job container_delete(PMX_UI)
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[516]: [8511f82d] -job container_delete(PMX_UI) = OK (0)
==> panamax-vm: Aug 19 20:50:52 panamax-vm systemd[1]: Started Panamax UI.
==> panamax-vm: Aug 19 20:50:52 panamax-vm docker[1392]: PMX_UI
==> panamax-vm: Aug 19 20:50:53 panamax-vm docker[516]: 2014/08/19 20:50:53 POST /v1.12/containers/create?name=PMX_UI
==> panamax-vm: Aug 19 20:50:53 panamax-vm docker[516]: [8511f82d] +job create(PMX_UI)
==> panamax-vm: Panamax restarted
0
waiting for panamax to start.....
.....................................................................................................................................................................................................................................................................................................................

CTRL-C and do panamax restart has the same problem..

**Comment by fiedl** [comment]
+1

Manually adding port forwarding for port 3000 allows to access the ui through http://localhost:3000. The terminal keeps reading "*waiting for panamax to start...*".

OS X Yosemite 10.10.1 (14B25), Vagrant 1.7.2, VirtualBox 4.3.20, Panamax 0.2.11.

**Comment by hudsonmendes** [comment]
I have added the port forward in my virtual box and still nothing happens.
Panamax install must have been running, by now, for 15 minutes.
Still printing: "==> panamax-vm: ."
Virutalbox 4.3.10
Vangrant 1.7.2

When I run "panamax -v", I get:
Local Panamax component versions:
   UI: 
  API: 
Latest Panamax component versions:
   UI: 0.2.15
  API: 0.3.0

Any logs that I can dig into?

**Comment by hudsonmendes** [comment]
After almost 20 minutes, it was UP!
I didn't do more than what was said here.
I did forward the 3000 and waited.
Seems to be part of it -> the waiting.
Thanks

**Comment by cakkineni** [comment]
Closing out this issue as its quite old, please open a new issue if you're still having problems.
