### ISSUE TITLE
Applications stop and there is no way to start them again

### ISSUE THREAD

**Issue by coen-hyde** [CenturyLinkLabs/panamax-coreos#31]
I'm experiencing an issue where containers stop running. I'm not sure why but once they've stopped there is no way to start them again. The applications activity log is empty (at least through the gui).

Is there a way I can find out why the applications stop? The application I'm playing with is the "MediaWiki 1.21 - NGINX and MySQL 5.5" template. First nginx stops then later mysql. Until it stops the application works fine.

**Comment by cakkineni** [comment]
@coen-hyde 

Closing out this issue as its pretty old, please open a new issue if you're still having problems.
