### ISSUE TITLE
Connection reset by peer while using cURL on installation scripts.

### ISSUE THREAD

**Issue by cdipietro** [CenturyLinkLabs/panamax-coreos#58]
Following the [install instructions for debian] (https://github.com/CenturyLinkLabs/panamax-ui/wiki/Installing-Panamax#debian-60-or-higher) I executed:
```bash
curl http://download.panamax.io/installer/ubuntu.sh | bash
```
And instantaneously I got the following error message:
```bash
curl: (56) Recv failure: Connection reset by peer
```
I managed to download the [ubuntu.sh] (http://download.panamax.io/installer/ubuntu.sh) installation script through my browser and tried to run it, but again I got the same error message. So, I manually edited the script to force the use of *wget* instead of *curl*. That made the trick and the installer was finally downloaded and located at *~/.panamax*.

Continuing with the installation, I ran:
```bash
panamax init
```
and after passing the virtual machine related questions, the init script tried to download the vagrant images using *curl*  and so getting the same error than in the previous attempts.

I think we can dismiss network and firewall issues as I've been able to reach the download server with the browser as well with  *wget*. Then, the reasons why the download server is tearing down connections established from *curl* are still unknown to me. I googled around to investigate the issue, but I wasn't able to find anything relevant.

FYI, I am runing a Debian 7 Linux on a x86_64 Intel Core I5 processor. More detailed specs below:

```bash
carlos@cdp-iway:~$ uname -a
Linux cdp-iway 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux

carlos@cdp-iway:~$ curl -V
curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

carlos@cdp-iway:~$ vagrant --version
Vagrant 1.6.5

carlos@cdp-iway:~$ virtualbox --help
virtualbox --help
Oracle VM VirtualBox Manager 4.3.16
(C) 2005-2014 Oracle Corporation
All rights reserved.

```

BTW, after hacking the installation scripts to use *wget* instead of *curl*, now I am standing on the same issue reported on #29 

Thanks in advance for your help.:+1:

**Comment by cakkineni** [comment]
@cdipietro 

Closing out this issue as its pretty old, please open a new issue if you're having problems.
