### ISSUE TITLE
0.3.2 installer - Windows

### ISSUE THREAD

**Issue by arnos** [CenturyLinkLabs/panamax-coreos#60]
I wanted to test the 0.3.2 installer script (instead of manually modifying the current installer)

Downloaded http://download.panamax.io/installer/panamax-0.3.2.tar.gz
instead of http://download.panamax.io/installer/panamax-latest.tar.gz

But when I executed the script I got the following error after downloading http://download.panamax.io/images.tar.gz

VBoxManage.exe: error: Format autodetect failed: VERR_FILE_NOT_FOUND

Which is strange as both scripts download the same images.tar.gz.

**Comment by cakkineni** [comment]
@arnos 

Closing out this issue as its pretty old, please open a new issue if you're still having problems
