### ISSUE TITLE
Accessing private docker registry outside panamax

### ISSUE THREAD

**Issue by gideonairex** [CenturyLinkLabs/panamax-coreos#69]
I have installed panamax and I want to access a private docker registry. I have added the ```docker-registry.crt``` at ```/etc/ssl/certs and update-ca-certificates```. I can access my registry using 
```bash 
curl -u docker:docker https://registry.docker.com
```
 and its okay but when I use 
```bash
docker login https://registry.docker.com
```
it returns
```bash
 Error response from daemon: Server Error: Post https://registry.docker.com/v1/users/: x509: certificate signed by unknown authority
```
Is there a way to add certs.d on docker itself like ```/etc/docker/certs.d/<registry>```.

**Comment by cakkineni** [comment]
@gideonairex 

Closing out this issue as its old, please open a new issue if you're still having issues.
