### ISSUE TITLE
Tar error running "panamax init"

### ISSUE THREAD

**Issue by gs-rstarr** [CenturyLinkLabs/panamax-coreos#70]
Running "panamax init" for the first time after successful homebrew installation yields the following output on my MacOS 10.10.2.  

Checking if required software is installed.

Vagrant 1.6 or newer installed.
Virtualbox 4.3 or newer installed.

Creating a new CoreOS VM...

<Then the following lines display over and over until Ctrl-C>

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Downloading images
######################################################################## 100.0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

**Comment by cakkineni** [comment]
@gs-rstarr 

Closing out this issue as its old. Please open a new issue if you are still having problems.
