### ISSUE TITLE
"uuidgen: command not found" during instalation

### ISSUE THREAD

**Issue by andredasilvapinto** [CenturyLinkLabs/panamax-coreos#81]
During instalation (or reinstalation) I get this error message:

```
HOME/.panamax/desktop: line 279: uuidgen: command not found
```

But everything seems to go just fine.

Is uuidgen a requirement or is it ok to go without it? And if it is a requirement shouldn't it be stated along VirtualBox and Vagrant in the documentation?

```
Local Panamax component versions:
   UI: 0.2.20
  API: 0.3.3
Local Panamax Installer version:
  0.6.3
```

**Comment by cakkineni** [comment]
@andredasilvapinto 

`uuidgen` is needed for some minor features of panamax and is not required for the core features. But we have added this for our next release and you should see it in the list. Thank you.
